import { PageContentSchema } from './types';

export const careerContent: PageContentSchema = {
  pageKey: 'career',
  label: 'Career',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      description: 'Bagian hero halaman Career.',
      fields: [
        { key: 'eyebrow', label: 'Eyebrow / Label atas', type: 'text' },
        { key: 'title', label: 'Judul Besar', type: 'text' },
        { key: 'description', label: 'Sub-judul / Deskripsi', type: 'multiline' },
        { key: 'button', label: 'Teks Tombol', type: 'text' },
      ],
      defaults: {
        eyebrow: 'Careers',
        title: 'Be our Starmaker',
        description: 'Join the Red Fitness Squad and help inspire others to get better every day!',
        button: 'Follow Us On Instagram',
      },
    },
    {
      key: 'culture',
      label: 'Budaya & Playbook',
      description: 'Section "Our Playbook" dan "Our Success Culture".',
      fields: [
        { key: 'playbook_heading', label: 'Playbook — Judul Utama', type: 'text' },
        { key: 'playbook1_title', label: 'Playbook 1 — Judul', type: 'text' },
        { key: 'playbook1_desc', label: 'Playbook 1 — Deskripsi', type: 'multiline' },
        { key: 'playbook2_title', label: 'Playbook 2 — Judul', type: 'text' },
        { key: 'playbook2_desc', label: 'Playbook 2 — Deskripsi', type: 'multiline' },
        { key: 'playbook3_title', label: 'Playbook 3 — Judul', type: 'text' },
        { key: 'playbook3_desc', label: 'Playbook 3 — Deskripsi', type: 'multiline' },
        { key: 'success_title_l1', label: 'Success Culture — Baris 1 Judul', type: 'text' },
        { key: 'success_title_l2', label: 'Success Culture — Baris 2 Judul (merah)', type: 'text' },
        { key: 'success_description', label: 'Success Culture — Deskripsi', type: 'multiline' },
        { key: 'culture1', label: 'Nilai 1', type: 'text' },
        { key: 'culture2', label: 'Nilai 2', type: 'text' },
        { key: 'culture3', label: 'Nilai 3', type: 'text' },
        { key: 'culture4', label: 'Nilai 4', type: 'text' },
        { key: 'culture5', label: 'Nilai 5', type: 'text' },
      ],
      defaults: {
        playbook_heading: 'OUR PLAYBOOK',
        playbook1_title: 'ALL ABOUT THE POSITIVE',
        playbook1_desc: "We're all about people power. And we've got your back all the way.",
        playbook2_title: 'WE KEEP IT HEALTHY',
        playbook2_desc: 'Work hard. Play hard. We celebrate loyalty, positivity and performance. With plenty of social activities to get you fired up.',
        playbook3_title: 'WE GROW TOGETHER',
        playbook3_desc: 'A great squad is what gets us ahead. So we go all out to help you grow.',
        success_title_l1: 'OUR SUCCESS',
        success_title_l2: 'CULTURE',
        success_description: "What makes Red Fitness an inspiring place to work? It's our Winning Ways. These five values drive everything we do, make us stand out, and power the way we motivate others to level up their lives.",
        culture1: 'WIN TOGETHER',
        culture2: 'AIM HIGHER',
        culture3: 'WE CARE',
        culture4: 'OWN IT',
        culture5: 'LOVE WHAT WE DO',
      },
    },
    {
      key: 'jobs',
      label: 'Lowongan Kerja & Cara Daftar',
      description: 'Judul "Jobs With Us", daftar lowongan, dan langkah pendaftaran.',
      fields: [
        { key: 'jobs_title_base', label: 'Jobs — Judul base', type: 'text' },
        { key: 'jobs_title_highlight', label: 'Jobs — Judul (merah)', type: 'text' },
        { key: 'job1_title', label: 'Lowongan 1 — Judul', type: 'text' },
        { key: 'job1_dept', label: 'Lowongan 1 — Departemen', type: 'text' },
        { key: 'job1_location', label: 'Lowongan 1 — Lokasi', type: 'text' },
        { key: 'job1_type', label: 'Lowongan 1 — Tipe', type: 'text' },
        { key: 'job2_title', label: 'Lowongan 2 — Judul', type: 'text' },
        { key: 'job2_dept', label: 'Lowongan 2 — Departemen', type: 'text' },
        { key: 'job2_location', label: 'Lowongan 2 — Lokasi', type: 'text' },
        { key: 'job2_type', label: 'Lowongan 2 — Tipe', type: 'text' },
        { key: 'job3_title', label: 'Lowongan 3 — Judul', type: 'text' },
        { key: 'job3_dept', label: 'Lowongan 3 — Departemen', type: 'text' },
        { key: 'job3_location', label: 'Lowongan 3 — Lokasi', type: 'text' },
        { key: 'job3_type', label: 'Lowongan 3 — Tipe', type: 'text' },
        { key: 'job4_title', label: 'Lowongan 4 — Judul', type: 'text' },
        { key: 'job4_dept', label: 'Lowongan 4 — Departemen', type: 'text' },
        { key: 'job4_location', label: 'Lowongan 4 — Lokasi', type: 'text' },
        { key: 'job4_type', label: 'Lowongan 4 — Tipe', type: 'text' },
        { key: 'steps_title_base', label: 'Cara Daftar — Judul base', type: 'text' },
        { key: 'steps_title_highlight', label: 'Cara Daftar — Judul (merah)', type: 'text' },
        { key: 'step1_title', label: 'Langkah 1 — Judul', type: 'text' },
        { key: 'step1_desc', label: 'Langkah 1 — Deskripsi', type: 'multiline' },
        { key: 'step2_title', label: 'Langkah 2 — Judul', type: 'text' },
        { key: 'step2_desc', label: 'Langkah 2 — Deskripsi (tanpa email)', type: 'multiline' },
        { key: 'step2_email', label: 'Langkah 2 — Alamat Email', type: 'text' },
        { key: 'step3_title', label: 'Langkah 3 — Judul', type: 'text' },
        { key: 'step3_desc', label: 'Langkah 3 — Deskripsi', type: 'multiline' },
      ],
      defaults: {
        jobs_title_base: 'JOBS',
        jobs_title_highlight: 'WITH US',
        job1_title: 'PERSONAL TRAINER',
        job1_dept: 'Fitness',
        job1_location: 'Indonesia',
        job1_type: 'Club',
        job2_title: 'MEMBERSHIP CONSULTANT',
        job2_dept: 'Sales',
        job2_location: 'Indonesia',
        job2_type: 'Club',
        job3_title: 'SALES MANAGER',
        job3_dept: 'Management',
        job3_location: 'Indonesia',
        job3_type: 'Club',
        job4_title: 'CLUB GENERAL MANAGER',
        job4_dept: 'Management',
        job4_location: 'Indonesia',
        job4_type: 'Club',
        steps_title_base: 'LIKE IT',
        steps_title_highlight: 'SO FAR?',
        step1_title: 'START PREPPING',
        step1_desc: "Get your act together and sort your resume. Double check the details so you're good to go.",
        step2_title: 'HIT US UP',
        step2_desc: "Tell us which job you want and drop your resume at the email below.",
        step2_email: 'hr.indonesia@evolutionwellness.co.id',
        step3_title: 'STANDBY',
        step3_desc: "We'll get in touch if there's a spot for you.",
      },
    },
    {
      key: 'cta',
      label: 'CTA Bawah Halaman',
      description: 'Dua kotak CTA: Free Trial dan Corporate.',
      fields: [
        { key: 'trial_title', label: 'CTA Free Trial — Judul', type: 'text' },
        { key: 'trial_description', label: 'CTA Free Trial — Deskripsi', type: 'multiline' },
        { key: 'trial_button', label: 'CTA Free Trial — Teks Tombol', type: 'text' },
        { key: 'corp_title', label: 'CTA Corporate — Judul', type: 'text' },
        { key: 'corp_description', label: 'CTA Corporate — Deskripsi', type: 'multiline' },
        { key: 'corp_button', label: 'CTA Corporate — Teks Tombol', type: 'text' },
      ],
      defaults: {
        trial_title: 'TRY US FOR FREE',
        trial_description: 'Get an exclusive FREE TRIAL experience. No strings attached.',
        trial_button: 'TRY NOW',
        corp_title: 'LOOKING FOR A CORPORATE DEAL?',
        corp_description: 'Get an exclusive FREE TRIAL experience. No strings attached.',
        corp_button: 'CHECK OUT NOW',
      },
    },
  ],
};
