import { PageContentSchema } from './types';

export const classesContent: PageContentSchema = {
  pageKey: 'classes',
  label: 'Classes',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      description: 'Bagian hero utama halaman Classes.',
      fields: [
        { key: 'eyebrow', label: 'Eyebrow / Tag', type: 'text' },
        { key: 'title', label: 'Judul', type: 'text' },
        { key: 'title_highlight', label: 'Judul (merah)', type: 'text' },
        { key: 'description', label: 'Deskripsi', type: 'multiline' },
        { key: 'button', label: 'Teks Tombol', type: 'text' },
      ],
      defaults: {
        eyebrow: 'Endless Options',
        title: '7,700 Classes',
        title_highlight: 'Every Month.',
        description: "Your toughest decision will be which of the 7,700 group fitness classes to try next.",
        button: 'Explore Classes',
      },
    },
    {
      key: 'signature',
      label: 'Signature Classes',
      description: 'Section slider kelas-kelas signature.',
      fields: [
        { key: 'eyebrow', label: 'Eyebrow / Tag', type: 'text' },
        { key: 'title', label: 'Judul', type: 'text' },
        { key: 'title_highlight', label: 'Judul (merah)', type: 'text' },
        { key: 'description', label: 'Deskripsi', type: 'multiline' },
        { key: 'cta_link', label: 'CTA bawah slider', type: 'text' },
        { key: 'sig1_title', label: 'Kelas 1 — Judul', type: 'text' },
        { key: 'sig2_title', label: 'Kelas 2 — Judul', type: 'text' },
        { key: 'sig3_title', label: 'Kelas 3 — Judul', type: 'text' },
        { key: 'sig4_title', label: 'Kelas 4 — Judul', type: 'text' },
        { key: 'sig5_title', label: 'Kelas 5 — Judul', type: 'text' },
      ],
      defaults: {
        eyebrow: 'Elite Programs',
        title: 'Signature',
        title_highlight: 'Classes.',
        description: 'Experience our signature classes, designed to get you training like a star.',
        cta_link: 'EXPLORE ALL CLASSES',
        sig1_title: 'DNA FLAVOR',
        sig2_title: 'DNA MASK',
        sig3_title: 'DNA INSANITY',
        sig4_title: 'SALTAR',
        sig5_title: 'DNA CORE',
      },
    },
    {
      key: 'time',
      label: 'Timetable CTA',
      description: 'Bagian "Class Times of the Week" dan dual CTA di bawahnya.',
      fields: [
        { key: 'schedule_eyebrow', label: 'Jadwal — Eyebrow', type: 'text' },
        { key: 'schedule_title', label: 'Jadwal — Judul', type: 'text' },
        { key: 'schedule_title_highlight', label: 'Jadwal — Judul (merah)', type: 'text' },
        { key: 'schedule_description', label: 'Jadwal — Deskripsi', type: 'multiline' },
        { key: 'schedule_button', label: 'Jadwal — Teks Tombol', type: 'text' },
        { key: 'trial_eyebrow', label: 'CTA Free Trial — Eyebrow', type: 'text' },
        { key: 'trial_title', label: 'CTA Free Trial — Judul', type: 'text' },
        { key: 'trial_title_highlight', label: 'CTA Free Trial — Judul (merah)', type: 'text' },
        { key: 'trial_description', label: 'CTA Free Trial — Deskripsi', type: 'multiline' },
        { key: 'trial_button', label: 'CTA Free Trial — Teks Tombol', type: 'text' },
        { key: 'corp_eyebrow', label: 'CTA Corporate — Eyebrow', type: 'text' },
        { key: 'corp_title', label: 'CTA Corporate — Judul', type: 'text' },
        { key: 'corp_title_highlight', label: 'CTA Corporate — Judul (merah)', type: 'text' },
        { key: 'corp_description', label: 'CTA Corporate — Deskripsi', type: 'multiline' },
        { key: 'corp_button', label: 'CTA Corporate — Teks Tombol', type: 'text' },
      ],
      defaults: {
        schedule_eyebrow: 'Schedule',
        schedule_title: 'Class Times Of',
        schedule_title_highlight: 'The Week.',
        schedule_description: 'Book our classes up to 6 days before they started.',
        schedule_button: 'View Timetable',
        trial_eyebrow: 'Trial Access',
        trial_title: 'Try Us For',
        trial_title_highlight: 'Free.',
        trial_description: 'Get an exclusive FREE TRIAL experience. No strings attached.',
        trial_button: 'Try Now',
        corp_eyebrow: 'B2B Solutions',
        corp_title: 'Corporate',
        corp_title_highlight: 'Deal.',
        corp_description: "Elevate your team's performance with our tailored corporate memberships.",
        corp_button: 'Check Out Now',
      },
    },
  ],
};
