import { PageContentSchema } from './types';

export const contactContent: PageContentSchema = {
  pageKey: 'contact',
  label: 'Personal Training',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      description: 'Bagian hero halaman Personal Training.',
      fields: [
        { key: 'eyebrow', label: 'Eyebrow / Tag', type: 'text' },
        { key: 'title', label: 'Judul', type: 'text' },
        { key: 'title_highlight', label: 'Judul (merah)', type: 'text' },
        { key: 'description', label: 'Deskripsi', type: 'multiline' },
        { key: 'button', label: 'Teks Tombol', type: 'text' },
      ],
      defaults: {
        eyebrow: 'Personal Training',
        title: 'Train Like',
        title_highlight: 'A Star.',
        description: 'Get maximum results with our StarMakers. Elevate your potential with a customized plan just for you.',
        button: 'Get Your Trainer',
      },
    },
    {
      key: 'fact',
      label: 'Keahlian Trainer (Did You Know / Committed to Quality)',
      description: 'Dua bagian: "Did You Know?" dan "Committed To Quality".',
      fields: [
        { key: 's1_eyebrow', label: 'S1 — Eyebrow', type: 'text' },
        { key: 's1_title', label: 'S1 — Judul', type: 'text' },
        { key: 's1_title_highlight', label: 'S1 — Judul (merah)', type: 'text' },
        { key: 's1_description', label: 'S1 — Deskripsi', type: 'multiline' },
        { key: 's1_label', label: 'S1 — Label kotak ("YOU\'LL GET")', type: 'text' },
        { key: 's1_point1', label: 'S1 — Poin 1', type: 'multiline' },
        { key: 's1_point2', label: 'S1 — Poin 2', type: 'multiline' },
        { key: 's2_eyebrow', label: 'S2 — Eyebrow', type: 'text' },
        { key: 's2_title', label: 'S2 — Judul', type: 'text' },
        { key: 's2_title_highlight', label: 'S2 — Judul (merah)', type: 'text' },
        { key: 's2_description', label: 'S2 — Deskripsi', type: 'multiline' },
      ],
      defaults: {
        s1_eyebrow: 'Expertise',
        s1_title: 'Did You',
        s1_title_highlight: 'Know?',
        s1_description: "Our StarMaker Instructors' strength? They're all certified trainers. Just so they can help you crush your goals.",
        s1_label: "YOU'LL GET",
        s1_point1: 'Tailormade fitness plan to match your goals.',
        s1_point2: 'Personal feedback to keep you motivated while you get supervised & fun sessions.',
        s2_eyebrow: 'Standard',
        s2_title: 'Committed',
        s2_title_highlight: 'To Quality.',
        s2_description: 'All our Certified Fitness Coaches are required to complete a vigorous foundation training program spanning 3 to 12 months. Our coaches are required to pass all exams before being allowed to train our clients.',
      },
    },
    {
      key: 'comparation',
      label: 'Perbandingan Paket & Proses',
      description: 'Tabel perbandingan paket dan slider "We Make Your Goal Our Job".',
      fields: [
        { key: 'eyebrow', label: 'Perbandingan — Eyebrow', type: 'text' },
        { key: 'title', label: 'Perbandingan — Judul', type: 'text' },
        { key: 'title_highlight', label: 'Perbandingan — Judul (merah)', type: 'text' },
        { key: 'cta_button', label: 'Perbandingan — Teks Tombol', type: 'text' },
        { key: 'process_eyebrow', label: 'Proses — Eyebrow', type: 'text' },
        { key: 'process_title', label: 'Proses — Judul (multi-baris OK)', type: 'multiline' },
        { key: 'process_title_highlight', label: 'Proses — Judul (merah)', type: 'text' },
        { key: 'process_description', label: 'Proses — Deskripsi', type: 'multiline' },
        { key: 'step1_title', label: 'Proses Langkah 1 — Judul', type: 'text' },
        { key: 'step1_desc', label: 'Proses Langkah 1 — Deskripsi', type: 'multiline' },
        { key: 'step2_title', label: 'Proses Langkah 2 — Judul', type: 'text' },
        { key: 'step2_desc', label: 'Proses Langkah 2 — Deskripsi', type: 'multiline' },
        { key: 'step3_title', label: 'Proses Langkah 3 — Judul', type: 'text' },
        { key: 'step3_desc', label: 'Proses Langkah 3 — Deskripsi', type: 'multiline' },
      ],
      defaults: {
        eyebrow: 'Compare Plans',
        title: 'Choose Your',
        title_highlight: 'Personal Trainer.',
        cta_button: 'Get Started Now',
        process_eyebrow: 'The Process',
        process_title: 'We Make Your Goal',
        process_title_highlight: 'Our Job.',
        process_description: "Your all-access to upping your fitness game. Dedicated, professional trainers to help you rock your journey.",
        step1_title: 'ASSESSMENTS',
        step1_desc: 'Get assessed with our exclusive tests.',
        step2_title: 'PREP FOR PEP',
        step2_desc: 'Your trainer crafts a custom regime.',
        step3_title: 'TRAIN HARD',
        step3_desc: 'Execute your plan with expert guidance.',
      },
    },
    {
      key: 'form',
      label: 'Form & FAQ',
      description: 'Form Free Trial, daftar manfaat, dan FAQ.',
      fields: [
        { key: 'form_eyebrow', label: 'Form — Eyebrow', type: 'text' },
        { key: 'form_title', label: 'Form — Judul', type: 'text' },
        { key: 'form_title_highlight', label: 'Form — Judul (merah)', type: 'text' },
        { key: 'form_description', label: 'Form — Sub-judul', type: 'text' },
        { key: 'form_button', label: 'Form — Teks Tombol', type: 'text' },
        { key: 'program_eyebrow', label: 'Program — Eyebrow', type: 'text' },
        { key: 'program_title', label: 'Program — Judul', type: 'text' },
        { key: 'program_title_highlight', label: 'Program — Judul (merah)', type: 'text' },
        { key: 'program_description', label: 'Program — Deskripsi', type: 'multiline' },
        { key: 'program_benefits_label', label: 'Program — Label kotak manfaat', type: 'text' },
        { key: 'benefit1', label: 'Manfaat 1', type: 'text' },
        { key: 'benefit2', label: 'Manfaat 2', type: 'text' },
        { key: 'benefit3', label: 'Manfaat 3', type: 'text' },
        { key: 'benefit4', label: 'Manfaat 4', type: 'text' },
        { key: 'benefit5', label: 'Manfaat 5', type: 'text' },
        { key: 'benefit6', label: 'Manfaat 6', type: 'text' },
        { key: 'faq_eyebrow', label: 'FAQ — Eyebrow', type: 'text' },
        { key: 'faq_title', label: 'FAQ — Judul', type: 'text' },
        { key: 'faq_title_highlight', label: 'FAQ — Judul (merah)', type: 'text' },
        { key: 'faq1_q', label: 'FAQ 1 — Pertanyaan', type: 'text' },
        { key: 'faq1_a', label: 'FAQ 1 — Jawaban', type: 'multiline' },
        { key: 'faq2_q', label: 'FAQ 2 — Pertanyaan', type: 'text' },
        { key: 'faq2_a', label: 'FAQ 2 — Jawaban', type: 'multiline' },
        { key: 'faq3_q', label: 'FAQ 3 — Pertanyaan', type: 'text' },
        { key: 'faq3_a', label: 'FAQ 3 — Jawaban', type: 'multiline' },
        { key: 'faq4_q', label: 'FAQ 4 — Pertanyaan', type: 'text' },
        { key: 'faq4_a', label: 'FAQ 4 — Jawaban', type: 'multiline' },
      ],
      defaults: {
        form_eyebrow: 'Limited Offer',
        form_title: 'Sign Up For A',
        form_title_highlight: 'Free Trial.',
        form_description: "We'll get in touch within 48 hours.",
        form_button: 'Submit Request',
        program_eyebrow: 'Join The Program',
        program_title: 'Personal Training',
        program_title_highlight: 'Made For You.',
        program_description: "Crush those goals with our experts. We don't do average. It's a custom, results-driven training vibe tailored specifically for your body and ambitions.",
        program_benefits_label: "YOU'LL ENJOY",
        benefit1: "Save up and own your fitness journey!",
        benefit2: "Certified Coaches on your schedule, your style.",
        benefit3: "Personalized plans.",
        benefit4: "Epic assessments.",
        benefit5: "MyCoach tracking.",
        benefit6: "Plus pro tips on nutrition.",
        faq_eyebrow: 'Get Answers',
        faq_title: 'Frequently Asked',
        faq_title_highlight: 'Questions.',
        faq1_q: 'CERTIFIED FITNESS COACHES: THE BENEFITS',
        faq1_a: 'Our coaches provide professional guidance, personalized programming, and the motivation you need to reach your goals safely and effectively.',
        faq2_q: 'DEFINING GOALS WITH CERTIFIED FITNESS COACHES',
        faq2_a: 'Your coach will perform assessments to understand your current level and help you set SMART (Specific, Measurable, Achievable, Relevant, Time-bound) goals.',
        faq3_q: 'HOW ARE FITNESS LEVELS ACCESSED?',
        faq3_a: 'We use a combination of postural analysis, dynamic movement screening, and strength/cardio testing to create your baseline.',
        faq4_q: 'ADAPTING WORKOUTS TO FIT CRAZY SCHEDULES',
        faq4_a: 'Flexibility is key. Our trainers work around your availability, offering sessions that fit into your busy lifestyle.',
      },
    },
  ],
};
