import { PageContentSchema } from './types';

export const pilatesContent: PageContentSchema = {
  pageKey: 'pilates-performer',
  label: 'Pilates Performer',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      description: 'Bagian hero halaman Pilates Performer.',
      fields: [
        { key: 'eyebrow', label: 'Eyebrow / Tag', type: 'text' },
        { key: 'title', label: 'Judul', type: 'text' },
        { key: 'title_highlight', label: 'Judul (merah)', type: 'text' },
        { key: 'description', label: 'Deskripsi', type: 'multiline' },
        { key: 'button', label: 'Teks Tombol', type: 'text' },
      ],
      defaults: {
        eyebrow: 'Premium Program',
        title: 'Pilates',
        title_highlight: 'Performer.',
        description: 'Elevate your core strength, flexibility, and posture with our exclusive Pilates Performer program — designed for all levels.',
        button: 'Join Now',
      },
    },
    {
      key: 'benefits',
      label: 'Manfaat Pilates',
      description: 'Section grid 6 manfaat Pilates.',
      fields: [
        { key: 'eyebrow', label: 'Eyebrow / Tag', type: 'text' },
        { key: 'title', label: 'Judul', type: 'text' },
        { key: 'title_highlight', label: 'Judul (merah)', type: 'text' },
        { key: 'description', label: 'Deskripsi', type: 'multiline' },
        { key: 'benefit1_title', label: 'Manfaat 1 — Judul', type: 'text' },
        { key: 'benefit1_desc', label: 'Manfaat 1 — Deskripsi', type: 'multiline' },
        { key: 'benefit2_title', label: 'Manfaat 2 — Judul', type: 'text' },
        { key: 'benefit2_desc', label: 'Manfaat 2 — Deskripsi', type: 'multiline' },
        { key: 'benefit3_title', label: 'Manfaat 3 — Judul', type: 'text' },
        { key: 'benefit3_desc', label: 'Manfaat 3 — Deskripsi', type: 'multiline' },
        { key: 'benefit4_title', label: 'Manfaat 4 — Judul', type: 'text' },
        { key: 'benefit4_desc', label: 'Manfaat 4 — Deskripsi', type: 'multiline' },
        { key: 'benefit5_title', label: 'Manfaat 5 — Judul', type: 'text' },
        { key: 'benefit5_desc', label: 'Manfaat 5 — Deskripsi', type: 'multiline' },
        { key: 'benefit6_title', label: 'Manfaat 6 — Judul', type: 'text' },
        { key: 'benefit6_desc', label: 'Manfaat 6 — Deskripsi', type: 'multiline' },
      ],
      defaults: {
        eyebrow: 'Why Pilates',
        title: 'The Benefits Of',
        title_highlight: 'Performance.',
        description: 'Pilates is more than exercise — it\'s a complete system that transforms how your body moves and performs.',
        benefit1_title: 'Core Strength',
        benefit1_desc: 'Build deep stabilizing muscles that support your spine and improve overall body control.',
        benefit2_title: 'Flexibility',
        benefit2_desc: 'Lengthen and mobilize muscles through controlled movement patterns designed for full range of motion.',
        benefit3_title: 'Injury Prevention',
        benefit3_desc: 'Strengthen underused muscles and correct muscular imbalances to protect joints long term.',
        benefit4_title: 'Mind-Body Connection',
        benefit4_desc: 'Train with precision and intention — every rep is purposeful, building awareness as well as strength.',
        benefit5_title: 'Better Posture',
        benefit5_desc: 'Realign your body from the inside out. Stand taller, move better, feel the difference daily.',
        benefit6_title: 'Progressive Performance',
        benefit6_desc: 'A structured program that evolves with you — from foundation to advanced performer levels.',
      },
    },
    {
      key: 'programs',
      label: 'Program Pilates',
      description: 'Daftar 4 program Pilates dan CTA bawah.',
      fields: [
        { key: 'eyebrow', label: 'Eyebrow / Tag', type: 'text' },
        { key: 'title', label: 'Judul', type: 'text' },
        { key: 'title_highlight', label: 'Judul (merah)', type: 'text' },
        { key: 'subtitle', label: 'Sub-judul (kanan)', type: 'multiline' },
        { key: 'prog1_title', label: 'Program 1 — Judul', type: 'text' },
        { key: 'prog1_level', label: 'Program 1 — Level', type: 'text' },
        { key: 'prog1_duration', label: 'Program 1 — Durasi', type: 'text' },
        { key: 'prog1_desc', label: 'Program 1 — Deskripsi', type: 'multiline' },
        { key: 'prog2_title', label: 'Program 2 — Judul', type: 'text' },
        { key: 'prog2_level', label: 'Program 2 — Level', type: 'text' },
        { key: 'prog2_duration', label: 'Program 2 — Durasi', type: 'text' },
        { key: 'prog2_desc', label: 'Program 2 — Deskripsi', type: 'multiline' },
        { key: 'prog3_title', label: 'Program 3 — Judul', type: 'text' },
        { key: 'prog3_level', label: 'Program 3 — Level', type: 'text' },
        { key: 'prog3_duration', label: 'Program 3 — Durasi', type: 'text' },
        { key: 'prog3_desc', label: 'Program 3 — Deskripsi', type: 'multiline' },
        { key: 'prog4_title', label: 'Program 4 — Judul', type: 'text' },
        { key: 'prog4_level', label: 'Program 4 — Level', type: 'text' },
        { key: 'prog4_duration', label: 'Program 4 — Durasi', type: 'text' },
        { key: 'prog4_desc', label: 'Program 4 — Deskripsi', type: 'multiline' },
        { key: 'cta_button', label: 'Teks Tombol CTA', type: 'text' },
      ],
      defaults: {
        eyebrow: 'Our Programs',
        title: 'Choose Your',
        title_highlight: 'Program.',
        subtitle: 'From beginner mat classes to advanced reformer sessions — find the program that fits your level and goals.',
        prog1_title: 'Reformer Pilates',
        prog1_level: 'All Levels',
        prog1_duration: '50 mins',
        prog1_desc: 'Using the Pilates Reformer machine to provide resistance-based training. Ideal for building functional strength with controlled, fluid motion.',
        prog2_title: 'Mat Pilates',
        prog2_level: 'Beginner – Intermediate',
        prog2_duration: '45 mins',
        prog2_desc: 'The foundation of Pilates. Body-weight exercises performed on a mat, focusing on core engagement, breath control, and spinal alignment.',
        prog3_title: 'Pilates Flow',
        prog3_level: 'Intermediate – Advanced',
        prog3_duration: '55 mins',
        prog3_desc: 'A dynamic class linking Pilates movements in a smooth sequence. Builds endurance, coordination, and full-body control.',
        prog4_title: 'Private Session',
        prog4_level: 'Personalised',
        prog4_duration: '60 mins',
        prog4_desc: '1-on-1 sessions with a certified Pilates instructor. Perfect for rehabilitation, specific goals, or learning correct technique.',
        cta_button: 'Start Your Program',
      },
    },
  ],
};
