import { PageContentSchema } from './types';

export const redSeitaiContent: PageContentSchema = {
  pageKey: 'red-seitai',
  label: 'Red Seitai Therapy',
  sections: [
    {
      key: 'hero',
      label: 'Hero',
      description: 'Bagian hero halaman Red Seitai Therapy.',
      fields: [
        { key: 'eyebrow', label: 'Eyebrow / Tag', type: 'text' },
        { key: 'title', label: 'Judul', type: 'text' },
        { key: 'title_highlight', label: 'Judul (merah)', type: 'text' },
        { key: 'description', label: 'Deskripsi', type: 'multiline' },
        { key: 'button1', label: 'Teks Tombol 1', type: 'text' },
        { key: 'button2', label: 'Teks Tombol 2', type: 'text' },
      ],
      defaults: {
        eyebrow: 'Wellness & Recovery',
        title: 'Red Seitai',
        title_highlight: 'Therapy.',
        description: 'Restore balance and relieve tension with our Red Seitai Therapy — a holistic body correction treatment tailored to your well-being.',
        button1: 'Book Session',
        button2: 'Learn More',
      },
    },
    {
      key: 'about',
      label: 'Tentang Red Seitai',
      description: 'Penjelasan Seitai dan 4 pilar manfaat.',
      fields: [
        { key: 'eyebrow', label: 'Eyebrow / Tag', type: 'text' },
        { key: 'title', label: 'Judul', type: 'text' },
        { key: 'title_highlight', label: 'Judul (merah)', type: 'text' },
        { key: 'paragraph1', label: 'Paragraf 1', type: 'multiline' },
        { key: 'paragraph2', label: 'Paragraf 2', type: 'multiline' },
        { key: 'paragraph3', label: 'Paragraf 3', type: 'multiline' },
        { key: 'pillar1', label: 'Pilar 1 — Label', type: 'text' },
        { key: 'pillar2', label: 'Pilar 2 — Label', type: 'text' },
        { key: 'pillar3', label: 'Pilar 3 — Label', type: 'text' },
        { key: 'pillar4', label: 'Pilar 4 — Label', type: 'text' },
        { key: 'stats_text', label: 'Strip Statistik — Teks', type: 'multiline' },
      ],
      defaults: {
        eyebrow: 'About Seitai',
        title: 'What Is',
        title_highlight: 'Red Seitai?',
        paragraph1: 'Seitai is a Japanese-origin bodywork discipline focused on restoring the body\'s natural balance. The word means "correct body" — and that\'s exactly what this therapy aims to achieve.',
        paragraph2: 'Red Seitai Therapy combines traditional manual techniques with modern physiological understanding to release tension, realign the skeletal structure, and support the body\'s self-healing capacity.',
        paragraph3: 'Unlike conventional massage, Seitai works on the root cause of discomfort — not just the symptoms — leaving you feeling lighter, more mobile, and deeply restored.',
        pillar1: 'Body Realignment',
        pillar2: 'Circulation Boost',
        pillar3: 'Stress Relief',
        pillar4: 'Holistic Recovery',
        stats_text: 'Trusted by athletes, office workers, and wellness seekers — Red Seitai is for anyone who wants to move and feel better every day.',
      },
    },
    {
      key: 'treatments',
      label: 'Treatment & CTA',
      description: 'Daftar 4 treatment dan tombol CTA.',
      fields: [
        { key: 'eyebrow', label: 'Eyebrow / Tag', type: 'text' },
        { key: 'title', label: 'Judul', type: 'text' },
        { key: 'title_highlight', label: 'Judul (merah)', type: 'text' },
        { key: 'description', label: 'Deskripsi', type: 'multiline' },
        { key: 't1_title', label: 'Treatment 1 — Judul', type: 'text' },
        { key: 't1_duration', label: 'Treatment 1 — Durasi', type: 'text' },
        { key: 't1_desc', label: 'Treatment 1 — Deskripsi', type: 'multiline' },
        { key: 't2_title', label: 'Treatment 2 — Judul', type: 'text' },
        { key: 't2_duration', label: 'Treatment 2 — Durasi', type: 'text' },
        { key: 't2_desc', label: 'Treatment 2 — Deskripsi', type: 'multiline' },
        { key: 't3_title', label: 'Treatment 3 — Judul', type: 'text' },
        { key: 't3_duration', label: 'Treatment 3 — Durasi', type: 'text' },
        { key: 't3_desc', label: 'Treatment 3 — Deskripsi', type: 'multiline' },
        { key: 't4_title', label: 'Treatment 4 — Judul', type: 'text' },
        { key: 't4_duration', label: 'Treatment 4 — Durasi', type: 'text' },
        { key: 't4_desc', label: 'Treatment 4 — Deskripsi', type: 'multiline' },
        { key: 'cta_button1', label: 'Teks Tombol 1', type: 'text' },
        { key: 'cta_button2', label: 'Teks Tombol 2', type: 'text' },
      ],
      defaults: {
        eyebrow: 'Our Treatments',
        title: 'Choose Your',
        title_highlight: 'Session.',
        description: 'Each session is tailored to your body\'s needs. Our certified therapists guide you through every step.',
        t1_title: 'Full Body Seitai',
        t1_duration: '60 mins',
        t1_desc: 'A complete head-to-toe body correction session. Addresses overall postural imbalances, releases tension stored across the entire musculoskeletal system.',
        t2_title: 'Spinal Correction',
        t2_duration: '45 mins',
        t2_desc: 'Targeted therapy focusing on the spine and supporting muscles. Ideal for office workers, people with sedentary lifestyles, or those experiencing back discomfort.',
        t3_title: 'Sports Recovery',
        t3_duration: '50 mins',
        t3_desc: 'Designed for athletes and active individuals. Focuses on recovering overworked muscles, reducing inflammation, and restoring peak mobility after intense training.',
        t4_title: 'Relaxation & Reset',
        t4_duration: '45 mins',
        t4_desc: 'A gentler Seitai session combining body alignment with deep relaxation techniques. Perfect for stress relief, mental fatigue, and overall renewal.',
        cta_button1: 'Book a Session',
        cta_button2: 'Contact Us',
      },
    },
  ],
};
